### ISSUE TITLE
Should sdist invoke builder?

### ISSUE THREAD

**Issue by agoose77** [jupyterlab/hatch-jupyter-builder#24]
This is more of a "desired behaviour" thread than a bug report.

To my mind, this build hook should not build the extension for the sdist. Off-hand, I feel that sdists should really contain as little generated code as possible. After all, whoever installs from the sdist will still (at present) run the builder anyway. 

What are your thoughts on doing nothing for the sdist, and only running the builder for the wheel?

**Comment by blink1073** [comment]
We've always shipped the JS assets with the sdist, so `node` wouldn't be required to build from the sdist.  I think it makes sense to allow an option to opt out of this behaviour though.
