### ISSUE TITLE
Unable to build jupyter-widgets/widget-ts-cookiecutter under 0.6.0

### ISSUE THREAD

**Issue by peytondmurray** [jupyterlab/hatch-jupyter-builder#65]
## Description

I'm trying to build an example widget using the jupyter-widgets cookiecutter: https://github.com/jupyter-widgets/widget-ts-cookiecutter. Using `hatch-jupyter-builder==0.5.3`, `pip install .` completes successfully. Under `hatch-jupyter-builder==0.6.0`, the build fails.

## Reproduce

1. `pip install cookiecutter jupyter lab`
2. `cookiecutter https://github.com/jupyter-widgets/widget-ts-cookiecutter`
3. Select all the default options
4. `cd myproject`
5. `pip install -e .`

This fails to build with the following error:

```
  Traceback (most recent call last):
    File "/home/pdmurray/.pyenv/versions/mambaforge/envs/myapp/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 177, in prepare_metadata_for_build_editable
      hook = backend.prepare_metadata_for_build_editable
  AttributeError: module 'hatchling.build' has no attribute 'prepare_metadata_for_build_editable'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/pdmurray/.pyenv/versions/mambaforge/envs/myapp/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/home/pdmurray/.pyenv/versions/mambaforge/envs/myapp/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/pdmurray/.pyenv/versions/mambaforge/envs/myapp/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 186, in prepare_metadata_for_build_editable
      whl_basename = build_hook(metadata_directory, config_settings)
    File "/tmp/pip-build-env-rz5poet1/overlay/lib/python3.10/site-packages/hatchling/build.py", line 61, in build_editable
      return os.path.basename(next(builder.build(wheel_directory, ['editable'])))
    File "/tmp/pip-build-env-rz5poet1/overlay/lib/python3.10/site-packages/hatchling/builders/plugin/interface.py", line 136, in build
      build_hook.initialize(version, build_data)
    File "/tmp/pip-build-env-rz5poet1/normal/lib/python3.10/site-packages/hatch_jupyter_builder/plugin.py", line 38, in initialize
      config = JupyterBuildConfig(**normalize_kwargs(self.config))  # type: ignore[arg-type]
  TypeError: JupyterBuildConfig.__init__() got an unexpected keyword argument 'dependencies'
  error: subprocess-exited-with-error
```

I've been playing around trying to get the widget cookiecutter to work for the past few hours. Then a little while ago this error started appearing. I saw that the issue was with `hatch_jupyter_builder`, and there's been a new release a few minutes ago, so I tried `v0.5.3` and it works.

## Expected behavior

The build completes successfully.

## Context

- Operating System and version: Linux 5.19.7-arch1-1

<details>
<summary>Here's my environment:</summary>

[~/Desktop/workspace/myproject]⟦myapp⟧$ mamba list
# packages in environment at /home/pdmurray/.pyenv/versions/mambaforge/envs/myapp:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
anyio                     3.6.1                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
asttokens                 2.0.8                    pypi_0    pypi
attrs                     22.1.0                   pypi_0    pypi
babel                     2.10.3                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.11.1                   pypi_0    pypi
bleach                    5.0.1                    pypi_0    pypi
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.6.15            ha878542_0    conda-forge
certifi                   2022.6.15                pypi_0    pypi
cffi                      1.15.1                   pypi_0    pypi
charset-normalizer        2.1.1                    pypi_0    pypi
debugpy                   1.6.3                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
executing                 1.0.0                    pypi_0    pypi
fastjsonschema            2.16.1                   pypi_0    pypi
idna                      3.3                      pypi_0    pypi
ipykernel                 6.15.2                   pypi_0    pypi
ipython                   8.5.0                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                8.0.2                    pypi_0    pypi
jedi                      0.18.1                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
json5                     0.9.10                   pypi_0    pypi
jsonschema                4.15.0                   pypi_0    pypi
jupyter-client            7.3.5                    pypi_0    pypi
jupyter-core              4.11.1                   pypi_0    pypi
jupyter-server            1.18.1                   pypi_0    pypi
jupyterlab                3.4.6                    pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-server         2.15.1                   pypi_0    pypi
jupyterlab-widgets        3.0.3                    pypi_0    pypi
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libsqlite                 3.39.3               h753d276_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.12               h166bdaf_2    conda-forge
lxml                      4.9.1                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mistune                   2.0.4                    pypi_0    pypi
myproject                 0.1.0.dev0               pypi_0    pypi
nbclassic                 0.4.3                    pypi_0    pypi
nbclient                  0.6.7                    pypi_0    pypi
nbconvert                 7.0.0                    pypi_0    pypi
nbformat                  5.4.0                    pypi_0    pypi
ncurses                   6.3                  h27087fc_1    conda-forge
nest-asyncio              1.5.5                    pypi_0    pypi
notebook                  6.4.12                   pypi_0    pypi
notebook-shim             0.1.0                    pypi_0    pypi
openssl                   3.0.5                h166bdaf_2    conda-forge
packaging                 21.3                     pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
prometheus-client         0.14.1                   pypi_0    pypi
prompt-toolkit            3.0.31                   pypi_0    pypi
psutil                    5.9.2                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pygments                  2.13.0                   pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyrsistent                0.18.1                   pypi_0    pypi
python                    3.10.6          ha86cf86_0_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2022.2.1                 pypi_0    pypi
pyzmq                     23.2.1                   pypi_0    pypi
readline                  8.1.2                h0f457ee_0    conda-forge
requests                  2.28.1                   pypi_0    pypi
send2trash                1.8.0                    pypi_0    pypi
setuptools                65.3.0             pyhd8ed1ab_1    conda-forge
six                       1.16.0                   pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
soupsieve                 2.3.2.post1              pypi_0    pypi
stack-data                0.5.0                    pypi_0    pypi
terminado                 0.15.0                   pypi_0    pypi
tinycss2                  1.1.1                    pypi_0    pypi
tk                        8.6.12               h27826a3_0    conda-forge
tornado                   6.2                      pypi_0    pypi
traitlets                 5.3.0                    pypi_0    pypi
tzdata                    2022c                h191b570_0    conda-forge
urllib3                   1.26.12                  pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.4.1                    pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
widgetsnbextension        4.0.3                    pypi_0    pypi
xz                        5.2.6                h166bdaf_0    conda-forge

</details>

**Comment by blink1073** [comment]
Thanks for the report @peytondmurray!  I yanked 0.6.0

**Comment by blink1073** [comment]
Okay, so we need to add a test case that actually uses this as a backend, in addition to fixing the bug.
