### ISSUE TITLE
Migration introduces absolute paths into `shared-data`

### ISSUE THREAD

**Issue by agoose77** [jupyterlab/hatch-jupyter-builder#72]
## Description / Reproduce

1. I ran `python3 -m hatch_jupyter_builder.migrate .` on the K3D repo.
2. It introduced absolute paths into the `shared-data` section.

`hatch-jupyter-builder == 0.6.2`

**Comment by blink1073** [comment]
The leading slash is not an absolute path on disk, it is interpreted as a https://git-scm.com/docs/gitignore#_pattern_format, meaning the root of the repo.

**Comment by blink1073** [comment]
Ah, understood, thanks for clarifying.
